CREATE TABLE IF NOT EXISTS EMPLOYEES (
EMPLOYEE_ID INT NOT NULL,
DEPARTMENT_ID INT NOT NULL UNIQUE,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES STAFF(ID),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
)